const userData = [
    {
        "id":1,
        "email":"test@gmail.com",
        "phone":2123123123,
        "department":"IT"
    },
    {
        "id":2,
        "email":"test@gmail.com",
        "phone":2123123123,
        "department":"IT"
    },
    {
        "id":3,
        "email":"test@gmail.com",
        "phone":2123123123,
        "department":"IT"
    },
    {
        "id":4,
        "email":"test@gmail.com",
        "phone":2123123123,
        "department":"IT"
    },
    {
        "id":5,
        "email":"test@gmail.com",
        "phone":2123123123,
        "department":"IT"
    },
    {
        "id":1,
        "email":"test@gmail.com",
        "phone":2123123123,
        "department":"IT"
    },
    {
        "id":6,
        "email":"test@gmail.com",
        "phone":2123123123,
        "department":"IT"
    },
    {
        "id":7,
        "email":"test@gmail.com",
        "phone":2123123123,
        "department":"IT"
    },
    {
        "id":8,
        "email":"test@gmail.com",
        "phone":2123123123,
        "department":"IT"
    },{
        "id":89,
        "email":"test@gmail.com",
        "phone":2123123123,
        "department":"IT"
    },
    {
        "id":11,
        "email":"test@gmail.com",
        "phone":2123123123,
        "department":"IT"
    }
]

export default userData;